/* Generated By:JJTree: Do not edit this line. ASTANDNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTANDNode extends SimpleNode {
  public ASTANDNode(int id) {
    super(id);
  }

  public ASTANDNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d9828895726f0485a2f3ef1dd8f13967 (do not edit this line) */
