/* Generated By:JJTree: Do not edit this line. ASTANNSIGNNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTANNSIGNNode extends SimpleNode {
  public ASTANNSIGNNode(int id) {
    super(id);
  }

  public ASTANNSIGNNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e3abc46dc09c76629da744db91976f5 (do not edit this line) */
