/* Generated By:JJTree: Do not edit this line. ASTASSIGNNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTASSIGNNode extends SimpleNode {
  public ASTASSIGNNode(int id) {
    super(id);
  }

  public ASTASSIGNNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=024eeff9b5cf9d984a7ce4619eccdad5 (do not edit this line) */
