/* Generated By:JJTree: Do not edit this line. ASTassignment.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTassignment extends SimpleNode {
  public ASTassignment(int id) {
    super(id);
  }

  public ASTassignment(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f291404f1d66ab18b137e0fcddada782 (do not edit this line) */
