/* Generated By:JJTree: Do not edit this line. ASTboolDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTboolDec extends SimpleNode {
  public ASTboolDec(int id) {
    super(id);
  }

  public ASTboolDec(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=236e0e8f9b2bf9c7a3489689043f859f (do not edit this line) */
