/* Generated By:JJTree: Do not edit this line. ASTboolDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTboolDeclaration extends SimpleNode {
  public ASTboolDeclaration(int id) {
    super(id);
  }

  public ASTboolDeclaration(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df3d7fcbced044da0aee352d04c37e81 (do not edit this line) */
