/* Generated By:JJTree: Do not edit this line. ASTbool.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbool extends SimpleNode {
    private String name;
  public ASTbool(int id) {
    super(id);
  }

  public ASTbool(Parse p, int id) {
    super(p, id);
  }
    
    public void setName(String n) {
        name = n;
    }
    
    /**
     * {@inheritDoc}
     * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
     */
    public String toString() {
        return "Bool: " + name;
    }
    public String getName(){return name;}

}
/* JavaCC - OriginalChecksum=30e73d393fcf01a751602f32d852b490 (do not edit this line) */
