/* Generated By:JJTree: Do not edit this line. ASTcondition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcondition extends SimpleNode {
  public ASTcondition(int id) {
    super(id);
  }

  public ASTcondition(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=25fce3284bc2f19bee641830de9200d5 (do not edit this line) */
