/* Generated By:JJTree: Do not edit this line. ASTcharDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcharDec extends SimpleNode {
  public ASTcharDec(int id) {
    super(id);
  }

  public ASTcharDec(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=66542265109a9d08e1db2ed933a125ac (do not edit this line) */
