/* Generated By:JJTree: Do not edit this line. ASTcharDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcharDeclaration extends SimpleNode {
  public ASTcharDeclaration(int id) {
    super(id);
  }

  public ASTcharDeclaration(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=83a036533a40ac305d96da285685a906 (do not edit this line) */
