/* Generated By:JJTree: Do not edit this line. ASTdeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdeclaration extends SimpleNode {
  public ASTdeclaration(int id) {
    super(id);
  }

  public ASTdeclaration(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=52b0ff753385b8eaa4d27278c73e393e (do not edit this line) */
