/* Generated By:JJTree: Do not edit this line. ASTDIVNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDIVNode extends SimpleNode {
  public ASTDIVNode(int id) {
    super(id);
  }

  public ASTDIVNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84c174ceae2c1cf44ea4ed534195d156 (do not edit this line) */
