/* Generated By:JJTree: Do not edit this line. ASTEQNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQNode extends SimpleNode {
  public ASTEQNode(int id) {
    super(id);
  }

  public ASTEQNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8233b38a1742c36cfdfd92cd9e9b303a (do not edit this line) */
