/* Generated By:JJTree: Do not edit this line. ASTexpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTexpression extends SimpleNode {
  public ASTexpression(int id) {
    super(id);
  }

  public ASTexpression(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f94a689b39319e23a40c6a21db46fc8 (do not edit this line) */
