/* Generated By:JJTree: Do not edit this line. ASTfactor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfactor extends SimpleNode {
  public ASTfactor(int id) {
    super(id);
  }

  public ASTfactor(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75d19a5ea33206f2f0f246f09afb898c (do not edit this line) */
