/* Generated By:JJTree: Do not edit this line. ASTGENode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGENode extends SimpleNode {
  public ASTGENode(int id) {
    super(id);
  }

  public ASTGENode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0809112b815806677bf2b4670aac5ef3 (do not edit this line) */
