/* Generated By:JJTree: Do not edit this line. ASTGTNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGTNode extends SimpleNode {
  public ASTGTNode(int id) {
    super(id);
  }

  public ASTGTNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6264d19a3f1826ad3f7d1eeb4ed3ae5d (do not edit this line) */
