/* Generated By:JJTree: Do not edit this line. ASTintDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTintDeclaration extends SimpleNode {
  public ASTintDeclaration(int id) {
    super(id);
  }

  public ASTintDeclaration(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e3916ebe614087981a262d1c599b2d5c (do not edit this line) */
