/* Generated By:JJTree: Do not edit this line. ASTids.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTids extends SimpleNode {
  public ASTids(int id) {
    super(id);
  }

  public ASTids(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=831c4590874992d33ded981f1bab9bc1 (do not edit this line) */
