/* Generated By:JJTree: Do not edit this line. ASTifstatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTifstatement extends SimpleNode {
  public ASTifstatement(int id) {
    super(id);
  }

  public ASTifstatement(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49dc01f1e9745bb18f0b5e37569c6c5e (do not edit this line) */
