/* Generated By:JJTree: Do not edit this line. ASTid.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTid extends SimpleNode {
    private String name;
  public ASTid(int id) {
    super(id);
  }

  public ASTid(Parse p, int id) {
    super(p, id);
  }
  public void setName(String n) {
        name = n;
    }
    
    /**
     * {@inheritDoc}
     * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
     */
  public String toString() {
        return "Id: " + name;
    }
    public String getName(){return name;}


}
/* JavaCC - OriginalChecksum=97b8bafde7ec413aac20cc6e04775d8f (do not edit this line) */
