/* Generated By:JJTree: Do not edit this line. ASTintDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTintDec extends SimpleNode {
  public ASTintDec(int id) {
    super(id);
  }

  public ASTintDec(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5b094317360f01b76ba646a5fd6ddff (do not edit this line) */
