/* Generated By:JJTree: Do not edit this line. ASTinteger.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTinteger extends SimpleNode {
    private String name;
  public ASTinteger(int id) {
    super(id);
  }

  public ASTinteger(Parse p, int id) {
    super(p, id);
  }
    public void setName(String n) {
        name = n;
    }
    
    /**
     * {@inheritDoc}
     * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
     */
    public String toString() {
        return "Integer: " + name;
    }
    public String getName(){return name;}
}
/* JavaCC - OriginalChecksum=af8aea412b942803b8b42226e7c9ceff (do not edit this line) */
