/* Generated By:JJTree: Do not edit this line. ASTLTNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLTNode extends SimpleNode {
  public ASTLTNode(int id) {
    super(id);
  }

  public ASTLTNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1df657ca7f68e76f8eb15c1f9346de4c (do not edit this line) */
