/* Generated By:JJTree: Do not edit this line. ASTLENode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLENode extends SimpleNode {
  public ASTLENode(int id) {
    super(id);
  }

  public ASTLENode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=273acb771c7b901d03ae95ee4c962779 (do not edit this line) */
