/* Generated By:JJTree: Do not edit this line. ASTMINUSNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMINUSNode extends SimpleNode {
  public ASTMINUSNode(int id) {
    super(id);
  }

  public ASTMINUSNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=019e08a6e1df7b8e5523360635232a38 (do not edit this line) */
