/* Generated By:JJTree: Do not edit this line. ASTMULTINode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMULTINode extends SimpleNode {
  public ASTMULTINode(int id) {
    super(id);
  }

  public ASTMULTINode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e89396a78a72fe4347c0e6e16dc4814 (do not edit this line) */
