/* Generated By:JJTree: Do not edit this line. ASTMODNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMODNode extends SimpleNode {
  public ASTMODNode(int id) {
    super(id);
  }

  public ASTMODNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a663d33000b7a99da56a1ec813702e0a (do not edit this line) */
