/* Generated By:JJTree: Do not edit this line. ASTNENode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNENode extends SimpleNode {
  public ASTNENode(int id) {
    super(id);
  }

  public ASTNENode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=51d64762693d1fe921433fe64e6553a0 (do not edit this line) */
