/* Generated By:JJTree: Do not edit this line. ASTORNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTORNode extends SimpleNode {
  public ASTORNode(int id) {
    super(id);
  }

  public ASTORNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4d0b68c0508c75083280f48a3b884e4 (do not edit this line) */
