/* Generated By:JJTree: Do not edit this line. ASTprogram.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprogram extends SimpleNode {
  public ASTprogram(int id) {
    super(id);
  }

  public ASTprogram(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=76b2ed241c2a7da17df2e73dd5a658ba (do not edit this line) */
