/* Generated By:JJTree: Do not edit this line. ASTPLUSNode.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPLUSNode extends SimpleNode {
  public ASTPLUSNode(int id) {
    super(id);
  }

  public ASTPLUSNode(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05c7b39879b53f1953b426f153c2d9c3 (do not edit this line) */
