/* Generated By:JJTree: Do not edit this line. ASTreal.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreal extends SimpleNode {
    private String name;
  public ASTreal(int id) {
    super(id);
  }

  public ASTreal(Parse p, int id) {
    super(p, id);
  }
    
    public void setName(String n) {
        name = n;
    }
    
    /**
     * {@inheritDoc}
     * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
     */
    public String toString() {
        return "Real: " + name;
    }
    public String getName(){return name;}
}
/* JavaCC - OriginalChecksum=404629b53bdadaecc8888537071ee2e5 (do not edit this line) */
