/* Generated By:JJTree: Do not edit this line. ASTrealDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrealDeclaration extends SimpleNode {
  public ASTrealDeclaration(int id) {
    super(id);
  }

  public ASTrealDeclaration(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b1d34b58fef26963a5785523646129b (do not edit this line) */
