/* Generated By:JJTree: Do not edit this line. ASTrealDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrealDec extends SimpleNode {
  public ASTrealDec(int id) {
    super(id);
  }

  public ASTrealDec(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c03499a1967cffc82557950ef5b76632 (do not edit this line) */
