/* Generated By:JJTree: Do not edit this line. ASTreadstatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreadstatement extends SimpleNode {
  public ASTreadstatement(int id) {
    super(id);
  }

  public ASTreadstatement(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e54a7f983eff7ed0bba5c0bd4f03fc3b (do not edit this line) */
