/* Generated By:JJTree: Do not edit this line. ASTstatements.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatements extends SimpleNode {
  public ASTstatements(int id) {
    super(id);
  }

  public ASTstatements(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=946bfc631d5a8d051ee73d9ebf3dc50a (do not edit this line) */
