/* Generated By:JJTree: Do not edit this line. ASTstring.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstring extends SimpleNode {
    private String name;
  public ASTstring(int id) {
    super(id);
  }

  public ASTstring(Parse p, int id) {
    super(p, id);
  }
    public void setName(String n) {
        name = n;
    }
    
    /**
     * {@inheritDoc}
     * @see org.javacc.examples.jjtree.eg2.SimpleNode#toString()
     */
    public String toString() {
        return "String: " + name;
    }
    public String getName(){return name;}
}
/* JavaCC - OriginalChecksum=c8922c165c2bd4807374831b8047ad0c (do not edit this line) */
