/* Generated By:JJTree: Do not edit this line. ASTstatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatement extends SimpleNode {
  public ASTstatement(int id) {
    super(id);
  }

  public ASTstatement(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b19d653f078ea531102cf145f2940443 (do not edit this line) */
