/* Generated By:JJTree: Do not edit this line. ASTstart.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstart extends SimpleNode {
  public ASTstart(int id) {
    super(id);
  }

  public ASTstart(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e20777e166fd60d21486ba4116c03ed (do not edit this line) */
