/* Generated By:JJTree: Do not edit this line. ASTterm.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTterm extends SimpleNode {
  public ASTterm(int id) {
    super(id);
  }

  public ASTterm(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f806203e98bf9cda38684d032d081474 (do not edit this line) */
