/* Generated By:JJTree: Do not edit this line. ASTwritestatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwritestatement extends SimpleNode {
  public ASTwritestatement(int id) {
    super(id);
  }

  public ASTwritestatement(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e8f548a769625b8a6c510e80b438ea38 (do not edit this line) */
