/* Generated By:JJTree: Do not edit this line. ASTwhilestatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwhilestatement extends SimpleNode {
  public ASTwhilestatement(int id) {
    super(id);
  }

  public ASTwhilestatement(Parse p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6d2510b73d29709df63f372ac05ed47 (do not edit this line) */
