/* Generated By:JavaCC: Do not edit this line. ParseTreeConstants.java Version 6.0_1 */
public interface ParseTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTSTATEMENTS = 2;
  public int JJTSTATEMENT = 3;
  public int JJTIFSTATEMENT = 4;
  public int JJTCONDITION = 5;
  public int JJTEQNODE = 6;
  public int JJTNENODE = 7;
  public int JJTGTNODE = 8;
  public int JJTLTNODE = 9;
  public int JJTLENODE = 10;
  public int JJTGENODE = 11;
  public int JJTANDNODE = 12;
  public int JJTORNODE = 13;
  public int JJTEXPRESSION = 14;
  public int JJTPLUSNODE = 15;
  public int JJTMINUSNODE = 16;
  public int JJTTERM = 17;
  public int JJTMULTINODE = 18;
  public int JJTDIVNODE = 19;
  public int JJTMODNODE = 20;
  public int JJTFACTOR = 21;
  public int JJTID = 22;
  public int JJTINTEGER = 23;
  public int JJTSTRING = 24;
  public int JJTREAL = 25;
  public int JJTBOOL = 26;
  public int JJTWHILESTATEMENT = 27;
  public int JJTVOID = 28;
  public int JJTINTDEC = 29;
  public int JJTREALDEC = 30;
  public int JJTBOOLDEC = 31;
  public int JJTCHARDEC = 32;
  public int JJTIDS = 33;
  public int JJTASSIGNNODE = 34;
  public int JJTREADSTATEMENT = 35;
  public int JJTWRITESTATEMENT = 36;


  public String[] jjtNodeName = {
    "start",
    "program",
    "statements",
    "statement",
    "ifstatement",
    "condition",
    "EQNode",
    "NENode",
    "GTNode",
    "LTNode",
    "LENode",
    "GENode",
    "ANDNode",
    "ORNode",
    "expression",
    "PLUSNode",
    "MINUSNode",
    "term",
    "MULTINode",
    "DIVNode",
    "MODNode",
    "factor",
    "id",
    "integer",
    "string",
    "real",
    "bool",
    "whilestatement",
    "void",
    "intDec",
    "realDec",
    "boolDec",
    "charDec",
    "ids",
    "ASSIGNNode",
    "readstatement",
    "writestatement",
  };
}
/* JavaCC - OriginalChecksum=4506467e5cde9cc8250302aeb24d867e (do not edit this line) */
